name: cs584-assignment1
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astroid=2.4.2
  - autopep8=1.5.4
  - blas=1.0
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - click=7.1.2
  - isort=5.5.2
  - joblib=0.16.0
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libstdcxx-ng=9.3.0
  - loguru=0.5.0
  - mccabe=0.6.1
  - mypy=0.782
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - numpy=1.19.1
  - openssl=1.1.1g
  - pandas=1.1.2
  - pip=20.2.3
  - psutil=5.7.2
  - pycodestyle=2.6.0
  - pylint=2.6.0
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-dotenv=0.14.0
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
