name: cs584-assignment1
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astroid=2.4.2
  - autopep8=1.5.4
  - blas=1.0
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - click=7.1.2
  - cycler=0.10.0
  - dbus=1.13.16
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - isort=5.5.2
  - joblib=0.16.0
  - jpeg=9b
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - loguru=0.5.0
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mypy=0.782
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - numpy=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.1.2
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.3
  - psutil=5.7.2
  - pycodestyle=2.6.0
  - pylint=2.6.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-dotenv=0.14.0
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
